services:
  personal-assistant:
    image: python:3.12-slim
    working_dir: /app
    command: >-
      bash -lc "python -m pip install --upgrade pip && pip install -r requirements.txt && uvicorn graphiti.web_admin.app:create_app --factory --host 0.0.0.0 --port 8000"
    volumes:
      - ./:/app
      - personal_assistant_state:/root/.graphiti_sync
      - pip_cache:/root/.cache/pip
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:5
    environment:
      - NEO4J_AUTH=neo4j/localgraph
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
volumes:
  personal_assistant_state:
  pip_cache:
